package ui

const (
	themeNameCatppuccin = "catppuccin"
	themeNameMonokai    = "monokai"
	themeNameTokyonight = "tokyonight"
)

var themeCatppuccin = Theme{
	ActiveTask:              "#a6e3a1",
	ActiveTaskBeginTime:     "#f38ba8",
	ActiveTasks:             "#89b4fa",
	FormContext:             "#cba6f7",
	FormFieldName:           "#a6e3a1",
	FormHelp:                "#6c7086",
	HelpMsg:                 "#89b4fa",
	HelpPrimary:             "#89b4fa",
	HelpSecondary:           "#cdd6f4",
	InactiveTasks:           "#6c7086",
	InitialHelpMsg:          "#f38ba8",
	ListItemDesc:            "#6c7086",
	ListItemTitle:           "#cdd6f4",
	RecordsBorder:           "#6c7086",
	RecordsDateRange:        "#cdd6f4",
	RecordsFooter:           "#f38ba8",
	RecordsHeader:           "#a6e3a1",
	RecordsHelp:             "#6c7086",
	TaskEntry:               "#a6e3a1",
	TaskLogDetailsViewTitle: "#f38ba8",
	TaskLogEntry:            "#cba6f7",
	TaskLogFormError:        "#f38ba8",
	TaskLogFormInfo:         "#cba6f7",
	TaskLogFormWarn:         "#fab387",
	TaskLogList:             "#89b4fa",
	Tasks: []string{
		"#74c7ec",
		"#89b4fa",
		"#89dceb",
		"#94e2d5",
		"#a6e3a1",
		"#b4befe",
		"#cba6f7",
		"#cdd6f4",
		"#eba0ac",
		"#f2cdcd",
		"#f38ba8",
		"#f5e0dc",
		"#f9e2af",
		"#fab387",
	},
	TitleForeground: "#1e1e2e",
	ToolName:        "#89b4fa",
	Tracking:        "#cba6f7",
}

var themeMonokai = Theme{
	ActiveTask:              "#a6e22e",
	ActiveTaskBeginTime:     "#f92672",
	ActiveTasks:             "#66d9ef",
	FormContext:             "#ae81ff",
	FormFieldName:           "#a6e22e",
	FormHelp:                "#75715e",
	HelpMsg:                 "#66d9ef",
	HelpPrimary:             "#66d9ef",
	HelpSecondary:           "#f8f8f2",
	InactiveTasks:           "#75715e",
	InitialHelpMsg:          "#f92672",
	ListItemDesc:            "#75715e",
	ListItemTitle:           "#f8f8f2",
	RecordsBorder:           "#75715e",
	RecordsDateRange:        "#f8f8f2",
	RecordsFooter:           "#f92672",
	RecordsHeader:           "#a6e22e",
	RecordsHelp:             "#75715e",
	TaskEntry:               "#a6e22e",
	TaskLogDetailsViewTitle: "#f92672",
	TaskLogEntry:            "#ae81ff",
	TaskLogFormError:        "#f92672",
	TaskLogFormInfo:         "#ae81ff",
	TaskLogFormWarn:         "#fd971f",
	TaskLogList:             "#66d9ef",
	Tasks: []string{
		"#f92672",
		"#a6e22e",
		"#66d9ef",
		"#ae81ff",
		"#fd971f",
		"#e6db74",
		"#f8f8f2",
		"#f92672",
		"#a6e22e",
		"#66d9ef",
		"#ae81ff",
		"#fd971f",
		"#e6db74",
		"#f8f8f2",
	},
	TitleForeground: "#272822",
	ToolName:        "#66d9ef",
	Tracking:        "#ae81ff",
}

var themeTokyonight = Theme{
	ActiveTask:              "#9ece6a",
	ActiveTaskBeginTime:     "#f7768e",
	ActiveTasks:             "#7aa2f7",
	FormContext:             "#bb9af7",
	FormFieldName:           "#9ece6a",
	FormHelp:                "#565f89",
	HelpMsg:                 "#7aa2f7",
	HelpPrimary:             "#7aa2f7",
	HelpSecondary:           "#c0caf5",
	InactiveTasks:           "#565f89",
	InitialHelpMsg:          "#f7768e",
	ListItemDesc:            "#565f89",
	ListItemTitle:           "#c0caf5",
	RecordsBorder:           "#565f89",
	RecordsDateRange:        "#c0caf5",
	RecordsFooter:           "#f7768e",
	RecordsHeader:           "#9ece6a",
	RecordsHelp:             "#565f89",
	TaskEntry:               "#9ece6a",
	TaskLogDetailsViewTitle: "#f7768e",
	TaskLogEntry:            "#bb9af7",
	TaskLogFormError:        "#f7768e",
	TaskLogFormInfo:         "#bb9af7",
	TaskLogFormWarn:         "#e0af68",
	TaskLogList:             "#7aa2f7",
	Tasks: []string{
		"#f7768e",
		"#9ece6a",
		"#7aa2f7",
		"#bb9af7",
		"#e0af68",
		"#7dcfff",
		"#73daca",
		"#ff9e64",
		"#c0caf5",
		"#2ac3de",
		"#f7768e",
		"#9ece6a",
		"#7aa2f7",
		"#bb9af7",
	},
	TitleForeground: "#1a1b26",
	ToolName:        "#7aa2f7",
	Tracking:        "#bb9af7",
}

func DefaultTheme() Theme {
	return Theme{
		ActiveTask:              "#8ec07c",
		ActiveTaskBeginTime:     "#d3869b",
		ActiveTasks:             "#fe8019",
		FormContext:             "#fabd2f",
		FormFieldName:           "#8ec07c",
		FormHelp:                "#928374",
		HelpMsg:                 "#83a598",
		HelpPrimary:             "#83a598",
		HelpSecondary:           "#bdae93",
		InactiveTasks:           "#928374",
		InitialHelpMsg:          "#a58390",
		ListItemDesc:            "#777777",
		ListItemTitle:           "#dddddd",
		RecordsBorder:           "#665c54",
		RecordsDateRange:        "#fabd2f",
		RecordsFooter:           "#ef8f62",
		RecordsHeader:           "#d85d5d",
		RecordsHelp:             "#928374",
		TaskEntry:               "#8ec07c",
		TaskLogDetailsViewTitle: "#d3869b",
		TaskLogEntry:            "#fabd2f",
		TaskLogFormError:        "#fb4934",
		TaskLogFormInfo:         "#d3869b",
		TaskLogFormWarn:         "#fe8019",
		TaskLogList:             "#b8bb26",
		Tasks: []string{
			"#d3869b",
			"#b5e48c",
			"#90e0ef",
			"#ca7df9",
			"#ada7ff",
			"#bbd0ff",
			"#48cae4",
			"#8187dc",
			"#ffb4a2",
			"#b8bb26",
			"#ffc6ff",
			"#4895ef",
			"#83a598",
			"#fabd2f",
		},
		TitleForeground: "#282828",
		ToolName:        "#fe8019",
		Tracking:        "#fabd2f",
	}
}

func BuiltInThemes() []string {
	return []string{
		themeNameCatppuccin,
		themeNameMonokai,
		themeNameTokyonight,
	}
}
