name: scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 10 * *'

jobs:
  virus-total:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up mise
        uses: jdx/mise-action@v4
        with:
          install_args: go goreleaser
      - name: Build binaries
        run: mise run release:build
      - name: List binaries
        run: |
          ls -lh ./dist/hours_*/hours
      - uses: dhth/composite-actions/.github/actions/scan-files@main
        with:
          files: './dist/hours_*/hours'
          vt-api-key: ${{ secrets.VT_API_KEY }}
